// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: clipboardSync.proto

package clipboardSync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClipBoardContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipBoardContent) Reset() {
	*x = ClipBoardContent{}
	mi := &file_clipboardSync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipBoardContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipBoardContent) ProtoMessage() {}

func (x *ClipBoardContent) ProtoReflect() protoreflect.Message {
	mi := &file_clipboardSync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipBoardContent.ProtoReflect.Descriptor instead.
func (*ClipBoardContent) Descriptor() ([]byte, []int) {
	return file_clipboardSync_proto_rawDescGZIP(), []int{0}
}

func (x *ClipBoardContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_clipboardSync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clipboardSync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_clipboardSync_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

var File_clipboardSync_proto protoreflect.FileDescriptor

const file_clipboardSync_proto_rawDesc = "" +
	"\n" +
	"\x13clipboardSync.proto\x1a\x1bgoogle/protobuf/empty.proto\"&\n" +
	"\x10ClipBoardContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"/\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId2\x9e\x01\n" +
	"\x0fClipSyncService\x12I\n" +
	"\x1fSubscribeClipBoardContentUpdate\x12\x11.SubscribeRequest\x1a\x11.ClipBoardContent0\x01\x12@\n" +
	"\x13sendClipBoardUpdate\x12\x11.ClipBoardContent\x1a\x16.google.protobuf.EmptyB\"Z github.com/YenXXXW/clipboardSyncb\x06proto3"

var (
	file_clipboardSync_proto_rawDescOnce sync.Once
	file_clipboardSync_proto_rawDescData []byte
)

func file_clipboardSync_proto_rawDescGZIP() []byte {
	file_clipboardSync_proto_rawDescOnce.Do(func() {
		file_clipboardSync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clipboardSync_proto_rawDesc), len(file_clipboardSync_proto_rawDesc)))
	})
	return file_clipboardSync_proto_rawDescData
}

var file_clipboardSync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clipboardSync_proto_goTypes = []any{
	(*ClipBoardContent)(nil), // 0: ClipBoardContent
	(*SubscribeRequest)(nil), // 1: SubscribeRequest
	(*emptypb.Empty)(nil),    // 2: google.protobuf.Empty
}
var file_clipboardSync_proto_depIdxs = []int32{
	1, // 0: ClipSyncService.SubscribeClipBoardContentUpdate:input_type -> SubscribeRequest
	0, // 1: ClipSyncService.sendClipBoardUpdate:input_type -> ClipBoardContent
	0, // 2: ClipSyncService.SubscribeClipBoardContentUpdate:output_type -> ClipBoardContent
	2, // 3: ClipSyncService.sendClipBoardUpdate:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clipboardSync_proto_init() }
func file_clipboardSync_proto_init() {
	if File_clipboardSync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clipboardSync_proto_rawDesc), len(file_clipboardSync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clipboardSync_proto_goTypes,
		DependencyIndexes: file_clipboardSync_proto_depIdxs,
		MessageInfos:      file_clipboardSync_proto_msgTypes,
	}.Build()
	File_clipboardSync_proto = out.File
	file_clipboardSync_proto_goTypes = nil
	file_clipboardSync_proto_depIdxs = nil
}
