// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: clipboardSync.proto

package clipboardSync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClipSyncService_SubscribeClipBoardContentUpdate_FullMethodName = "/ClipSyncService/SubscribeClipBoardContentUpdate"
	ClipSyncService_SendClipBoardUpdate_FullMethodName             = "/ClipSyncService/sendClipBoardUpdate"
)

// ClipSyncServiceClient is the client API for ClipSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClipSyncServiceClient interface {
	SubscribeClipBoardContentUpdate(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClipBoardContent], error)
	SendClipBoardUpdate(ctx context.Context, in *ClipBoardContent, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clipSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClipSyncServiceClient(cc grpc.ClientConnInterface) ClipSyncServiceClient {
	return &clipSyncServiceClient{cc}
}

func (c *clipSyncServiceClient) SubscribeClipBoardContentUpdate(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClipBoardContent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClipSyncService_ServiceDesc.Streams[0], ClipSyncService_SubscribeClipBoardContentUpdate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ClipBoardContent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClipSyncService_SubscribeClipBoardContentUpdateClient = grpc.ServerStreamingClient[ClipBoardContent]

func (c *clipSyncServiceClient) SendClipBoardUpdate(ctx context.Context, in *ClipBoardContent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClipSyncService_SendClipBoardUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClipSyncServiceServer is the server API for ClipSyncService service.
// All implementations must embed UnimplementedClipSyncServiceServer
// for forward compatibility.
type ClipSyncServiceServer interface {
	SubscribeClipBoardContentUpdate(*SubscribeRequest, grpc.ServerStreamingServer[ClipBoardContent]) error
	SendClipBoardUpdate(context.Context, *ClipBoardContent) (*emptypb.Empty, error)
	mustEmbedUnimplementedClipSyncServiceServer()
}

// UnimplementedClipSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClipSyncServiceServer struct{}

func (UnimplementedClipSyncServiceServer) SubscribeClipBoardContentUpdate(*SubscribeRequest, grpc.ServerStreamingServer[ClipBoardContent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeClipBoardContentUpdate not implemented")
}
func (UnimplementedClipSyncServiceServer) SendClipBoardUpdate(context.Context, *ClipBoardContent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendClipBoardUpdate not implemented")
}
func (UnimplementedClipSyncServiceServer) mustEmbedUnimplementedClipSyncServiceServer() {}
func (UnimplementedClipSyncServiceServer) testEmbeddedByValue()                         {}

// UnsafeClipSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClipSyncServiceServer will
// result in compilation errors.
type UnsafeClipSyncServiceServer interface {
	mustEmbedUnimplementedClipSyncServiceServer()
}

func RegisterClipSyncServiceServer(s grpc.ServiceRegistrar, srv ClipSyncServiceServer) {
	// If the following call pancis, it indicates UnimplementedClipSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClipSyncService_ServiceDesc, srv)
}

func _ClipSyncService_SubscribeClipBoardContentUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClipSyncServiceServer).SubscribeClipBoardContentUpdate(m, &grpc.GenericServerStream[SubscribeRequest, ClipBoardContent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClipSyncService_SubscribeClipBoardContentUpdateServer = grpc.ServerStreamingServer[ClipBoardContent]

func _ClipSyncService_SendClipBoardUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipBoardContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipSyncServiceServer).SendClipBoardUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipSyncService_SendClipBoardUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipSyncServiceServer).SendClipBoardUpdate(ctx, req.(*ClipBoardContent))
	}
	return interceptor(ctx, in, info, handler)
}

// ClipSyncService_ServiceDesc is the grpc.ServiceDesc for ClipSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClipSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClipSyncService",
	HandlerType: (*ClipSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendClipBoardUpdate",
			Handler:    _ClipSyncService_SendClipBoardUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeClipBoardContentUpdate",
			Handler:       _ClipSyncService_SubscribeClipBoardContentUpdate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clipboardSync.proto",
}
